version: "3.8"

services:
  bff:
    build: ./backend-bff
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - FRONTEND_URL=http://localhost:5173
      - ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3000
    volumes:
      - ./backend-bff:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network

  # Frontend Vue
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=https://bff-b.fly.dev/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - bff
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
